// imports removed

class Transaction {
    constructor({ type, amount, category, description, date, recurring = false, userId }) {
        this.id = generateId();
        this.userId = userId;
        this.type = type; // 'income' | 'expense'
        this.amount = parseFloat(amount);
        this.category = category;
        this.description = description;
        this.date = date; // YYYY-MM-DD
        this.recurring = recurring;
        this.createdAt = new Date().toISOString();
    }
}

class TransactionManager {
    constructor() {
        this.transactions = storage.load(storage.KEYS.TRANSACTIONS) || [];
    }

    _save() {
        storage.save(storage.KEYS.TRANSACTIONS, this.transactions);
    }

    /**
     * Add a new transaction
     */
    add(transactionData) {
        if (!transactionData.amount || transactionData.amount <= 0) {
            throw new Error('Amount must be greater than 0');
        }
        if (!transactionData.description || !transactionData.category || !transactionData.date) {
            throw new Error('All fields are required');
        }

        const transaction = new Transaction(transactionData);
        this.transactions.unshift(transaction); // Add to beginning
        
        // Sort by date descending
        this.transactions.sort((a, b) => new Date(b.date) - new Date(a.date));
        
        this._save();
        return transaction;
    }

    /**
     * Remove a transaction by ID
     */
    remove(id) {
        this.transactions = this.transactions.filter(t => t.id !== id);
        this._save();
    }

    /**
     * Get all transactions for a user
     */
    getAll(userId) {
        return this.transactions.filter(t => t.userId === userId);
    }

    /**
     * Get transactions by month (YYYY-MM)
     */
    getByMonth(userId, monthYear) {
        return this.getAll(userId).filter(t => getMonthYear(t.date) === monthYear);
    }

    /**
     * Search and filter transactions
     */
    filterAndSearch(userId, { query = '', type = 'all', category = 'all', month = 'all' }) {
        let results = this.getAll(userId);

        if (type !== 'all') {
            results = results.filter(t => t.type === type);
        }

        if (category !== 'all') {
            results = results.filter(t => t.category === category);
        }

        if (month !== 'all') {
            results = results.filter(t => getMonthYear(t.date) === month);
        }

        if (query) {
            const lowerQuery = query.toLowerCase();
            results = results.filter(t => 
                t.description.toLowerCase().includes(lowerQuery) || 
                t.category.toLowerCase().includes(lowerQuery)
            );
        }

        return results;
    }

    /**
     * Get total income for a user (optionally by month)
     */
    getTotalIncome(userId, monthYear = null) {
        const transactions = monthYear ? this.getByMonth(userId, monthYear) : this.getAll(userId);
        return transactions
            .filter(t => t.type === 'income')
            .reduce((sum, t) => sum + t.amount, 0);
    }

    /**
     * Get total expenses for a user (optionally by month)
     */
    getTotalExpenses(userId, monthYear = null) {
        const transactions = monthYear ? this.getByMonth(userId, monthYear) : this.getAll(userId);
        return transactions
            .filter(t => t.type === 'expense')
            .reduce((sum, t) => sum + t.amount, 0);
    }

    /**
     * Get current balance
     */
    getBalance(userId) {
        return this.getTotalIncome(userId) - this.getTotalExpenses(userId);
    }

    /**
     * Get expense breakdown by category for a month
     */
    getCategoryBreakdown(userId, monthYear) {
        const expenses = this.getByMonth(userId, monthYear).filter(t => t.type === 'expense');
        const breakdown = {};
        
        expenses.forEach(t => {
            if (!breakdown[t.category]) {
                breakdown[t.category] = 0;
            }
            breakdown[t.category] += t.amount;
        });

        // Convert to array and sort by amount desc
        return Object.entries(breakdown)
            .map(([category, amount]) => ({ category, amount }))
            .sort((a, b) => b.amount - a.amount);
    }

    /**
     * Process recurring transactions for the current month
     */
    processRecurring(userId) {
        const currentMonth = getMonthYear();
        const allUserTrans = this.getAll(userId);
        
        // Find recurring transactions that don't have an entry for the current month yet
        const recurringTrans = allUserTrans.filter(t => t.recurring);
        const processedSignatures = new Set(
            allUserTrans
                .filter(t => t.isAutoGenerated && getMonthYear(t.date) === currentMonth)
                .map(t => `${t.category}-${t.description}-${t.amount}`)
        );

        let addedCount = 0;

        // Note: For a robust system, we would group recurring templates. 
        // Here we just look at past recurring marked transactions and ensure one exists this month
        
        // Find unique recurring templates (using the most recent one of each type)
        const templates = {};
        recurringTrans.forEach(t => {
            const sig = `${t.category}-${t.description}-${t.amount}`;
            if (!templates[sig] || new Date(t.date) > new Date(templates[sig].date)) {
                templates[sig] = t;
            }
        });

        Object.values(templates).forEach(template => {
            const sig = `${template.category}-${template.description}-${template.amount}`;
            
            // If we haven't auto-generated this for the current month, and the original wasn't from THIS month
            if (!processedSignatures.has(sig) && getMonthYear(template.date) !== currentMonth) {
                // Auto generate
                const newDate = new Date(); // Today
                
                const newTrans = new Transaction({
                    type: template.type,
                    amount: template.amount,
                    category: template.category,
                    description: template.description,
                    date: newDate.toISOString().split('T')[0],
                    recurring: true,
                    userId: userId
                });
                
                newTrans.isAutoGenerated = true; // Flag to prevent multiple generation
                
                this.transactions.push(newTrans);
                addedCount++;
            }
        });

        if (addedCount > 0) {
            this.transactions.sort((a, b) => new Date(b.date) - new Date(a.date));
            this._save();
        }
        
        return addedCount;
    }

    /**
     * Undo (delete) the last transaction added by the user
     */
    undoLast(userId) {
        const userTrans = this.getAll(userId);
        if (userTrans.length === 0) return null;
        
        // They are sorted by date, but we want the most recently CREATED one
        // Because of our simple model, we can find the one with the newest createdAt
        let latest = userTrans[0];
        for (let i = 1; i < userTrans.length; i++) {
            if (new Date(userTrans[i].createdAt) > new Date(latest.createdAt)) {
                latest = userTrans[i];
            }
        }
        
        this.remove(latest.id);
        return latest;
    }

    /**
     * Export user transactions to JSON
     */
    exportToJSON(userId) {
        const data = this.getAll(userId);
        return JSON.stringify(data, null, 2);
    }
}

const transactionManager = new TransactionManager();
